# Generated by Django 4.1.6 on 2023-05-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='Default question text', max_length=200),
        ),
    ]
